export interface FestivalThemePreset {
  id: string;
  name: string;
  festival: string;
  tagline: string;
  icon: string;
  category: 'FESTIVAL' | 'SEASONAL' | 'SIGNATURE';
  mode: 'LIGHT' | 'DARK';
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  backgroundColor: string;
  cardBg: string;
  textColor: string;
  textMuted: string;
  glowColor: string;
  borderColor: string;
  announcementTicker: string;
  heroHeadline: string;
  heroSubtitle: string;
  heroBadge: string;
  godImageUrl: string;
  godName: string;
  festivalBannerUrl: string;
  blessingQuote: string;
  bgPattern: 'rangoli' | 'mandala' | 'gulal-splash' | 'diya-pattern' | 'crescent-stars' | 'lotus-waves' | 'snow-flakes' | 'none';
  ambientEffect: 'diya-sparks' | 'gulal-burst' | 'golden-petals' | 'snow-stars' | 'crescent-stars' | 'peacock-aura' | 'roastery-gold' | 'none';
  paletteClusters: string[];
}

export const PRESET_FESTIVAL_THEMES: FestivalThemePreset[] = [
  // 1. DIWALI (DARK / MIDNIGHT)
  {
    id: 'diwali-dark',
    name: 'Diwali Mahotsav (Midnight Gold & Sacred Diyas)',
    festival: 'Deepavali / Diwali',
    tagline: 'Royal Diya Glow with Warm Crimson & 24K Gold Embers',
    icon: '🪔',
    category: 'FESTIVAL',
    mode: 'DARK',
    primaryColor: '#FFD700',
    secondaryColor: '#FF5722',
    accentColor: '#FF8A65',
    backgroundColor: '#0A0612',
    cardBg: '#150C24',
    textColor: '#FFF9E6',
    textMuted: '#D1C4E9',
    glowColor: 'rgba(255, 215, 0, 0.45)',
    borderColor: 'rgba(255, 215, 0, 0.35)',
    announcementTicker: '🪔 Shubh Deepavali! 100% Pure W180 King Jumbo Cashews & Royal Festive Gift Hampers Ready for Dispatch',
    heroHeadline: 'Royal Diwali Celebration Handcrafted Cashew Hampers',
    heroSubtitle: 'Celebrate the Festival of Lights with our finest vacuum-sealed King Jumbo W180 & gourmet roasted varieties from Uppal Roastery.',
    heroBadge: 'Diwali Grand Festivity',
    godImageUrl: 'https://images.unsplash.com/photo-1605647540924-852290f6b0d5?w=600&auto=format&fit=crop&q=80',
    godName: 'Goddess Lakshmi & Sacred Diyas',
    festivalBannerUrl: 'https://images.unsplash.com/photo-1514195037031-83d60ed3b448?w=1200&auto=format&fit=crop&q=80',
    blessingQuote: 'ॐ श्रीं ह्रीं क्लीं त्रिभुवन महालक्ष्म्यै नमः • Shubh Deepavali Blessings',
    bgPattern: 'diya-pattern',
    ambientEffect: 'diya-sparks',
    paletteClusters: ['#FFD700', '#FF5722', '#FF8A65', '#150C24'],
  },

  // 2. DIWALI (LIGHT / DAY FESTIVITY)
  {
    id: 'diwali-light',
    name: 'Diwali Auspicious Morning (Royal Ivory & Marigold Gold)',
    festival: 'Deepavali / Diwali',
    tagline: 'Bright Festive Ivory with Marigold Amber & Shimmering Gold',
    icon: '🪔',
    category: 'FESTIVAL',
    mode: 'LIGHT',
    primaryColor: '#B45309',
    secondaryColor: '#D97706',
    accentColor: '#EA580C',
    backgroundColor: '#FFFDF7',
    cardBg: '#FFFFFF',
    textColor: '#1E1B18',
    textMuted: '#6B7280',
    glowColor: 'rgba(217, 119, 6, 0.35)',
    borderColor: 'rgba(217, 119, 6, 0.25)',
    announcementTicker: '🪔 Auspicious Diwali Morning • Special Discounts on W180 Cashews & Festive Gifting Tins',
    heroHeadline: 'Divine Handpicked Cashews for Pure Festive Celebrations',
    heroSubtitle: 'Gilded gift packs prepared with utmost sanctity at our Uppal facility in Hyderabad.',
    heroBadge: 'Diwali Morning Bliss',
    godImageUrl: 'https://images.unsplash.com/photo-1605647540924-852290f6b0d5?w=600&auto=format&fit=crop&q=80',
    godName: 'Maha Lakshmi Blessings',
    festivalBannerUrl: 'https://images.unsplash.com/photo-1514195037031-83d60ed3b448?w=1200&auto=format&fit=crop&q=80',
    blessingQuote: 'शुभ दीपावली • May Goddess Lakshmi illuminate your life with health, happiness, and prosperity.',
    bgPattern: 'rangoli',
    ambientEffect: 'golden-petals',
    paletteClusters: ['#B45309', '#D97706', '#EA580C', '#FFFDF7'],
  },

  // 3. HOLI (DARK / CYBER GULAL)
  {
    id: 'holi-dark',
    name: 'Holi Rangotsav (Gulal Pink & Electric Cyan Splash)',
    festival: 'Holi / Rangotsav',
    tagline: 'Vibrant Splash of Gulal Pink, Sunny Yellow & Electric Cyan',
    icon: '🎨',
    category: 'FESTIVAL',
    mode: 'DARK',
    primaryColor: '#FF007F',
    secondaryColor: '#FFBE0B',
    accentColor: '#00F5D4',
    backgroundColor: '#0D0818',
    cardBg: '#1B1033',
    textColor: '#FFFFFF',
    textMuted: '#C4B5FD',
    glowColor: 'rgba(255, 0, 127, 0.45)',
    borderColor: 'rgba(0, 245, 212, 0.35)',
    announcementTicker: '🎨 Happy Holi! Elevate Your Celebrations with Spicy Peri Peri & Tandoori Gourmet Roasted Cashews',
    heroHeadline: 'Vibrant Festive Crunch for Your Holi Celebrations',
    heroSubtitle: 'Hand-tossed with aromatic spices, Himalayan rock salt, and fiery peppers. The ultimate festive snack for your guests.',
    heroBadge: 'Rangotsav Special',
    godImageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
    godName: 'Radha Krishna Rangotsav',
    festivalBannerUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1200&auto=format&fit=crop&q=80',
    blessingQuote: 'होली के पावन पर्व पर आपके जीवन में आनंद और उमंग के अनगिनत रंग बरसें!',
    bgPattern: 'gulal-splash',
    ambientEffect: 'gulal-burst',
    paletteClusters: ['#FF007F', '#FFBE0B', '#00F5D4', '#1B1033'],
  },

  // 4. HOLI (LIGHT / SPRING RANG)
  {
    id: 'holi-light',
    name: 'Holi Spring Carnival (Pastel Peach, Rose Pink & Mint)',
    festival: 'Holi / Rangotsav',
    tagline: 'Fresh Spring Daybreak with Soft Rose Gulal & Pichkari Mint',
    icon: '🎨',
    category: 'FESTIVAL',
    mode: 'LIGHT',
    primaryColor: '#E11D48',
    secondaryColor: '#0D9488',
    accentColor: '#F59E0B',
    backgroundColor: '#FFF5F8',
    cardBg: '#FFFFFF',
    textColor: '#1F2937',
    textMuted: '#6B7280',
    glowColor: 'rgba(225, 29, 72, 0.35)',
    borderColor: 'rgba(13, 148, 136, 0.3)',
    announcementTicker: '🎨 Holi Spring Mela! Gourmet Spiced & Tangy Cashews Perfect for Party Platters',
    heroHeadline: 'Joyful & Flavorful Crunch for Your Holi Gathering',
    heroSubtitle: 'Crunchy, freshly roasted cashews coated with tangy mint, pudina, and authentic Indian masala.',
    heroBadge: 'Holi Spring Edition',
    godImageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
    godName: 'Joyous Spring Celebrations',
    festivalBannerUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1200&auto=format&fit=crop&q=80',
    blessingQuote: 'Happy Holi! May your celebrations be filled with vibrant happiness, peace, and prosperity.',
    bgPattern: 'gulal-splash',
    ambientEffect: 'gulal-burst',
    paletteClusters: ['#E11D48', '#0D9488', '#F59E0B', '#FFF5F8'],
  },

  // 5. GANESH CHATURTHI (DARK / DIVINE KESARI)
  {
    id: 'ganesh-dark',
    name: 'Ganesh Chaturthi (Kesari Saffron & Auspicious Ochre)',
    festival: 'Ganesh Chaturthi / Vinayaka Chavithi',
    tagline: 'Divine Saffron Ochre with Sacred Kumkum & Gold Radiance',
    icon: '🐘',
    category: 'FESTIVAL',
    mode: 'DARK',
    primaryColor: '#FF7700',
    secondaryColor: '#D4AF37',
    accentColor: '#E63946',
    backgroundColor: '#120704',
    cardBg: '#210E07',
    textColor: '#FFF7ED',
    textMuted: '#FED7AA',
    glowColor: 'rgba(255, 119, 0, 0.45)',
    borderColor: 'rgba(212, 175, 55, 0.4)',
    announcementTicker: '🐘 Ganpati Bappa Morya! Purest W180 King Whole Cashews for Modak Prasadam & Celebrations',
    heroHeadline: 'Divine Handpicked Cashews for Auspicious Prasadam',
    heroSubtitle: 'Sidhi Vinayaka Traders presents whole white kernel cashews for traditional delicacies and offerings.',
    heroBadge: 'Vinayaka Chavithi Special',
    godImageUrl: 'https://images.unsplash.com/photo-1567591974584-f1832dfcad52?w=600&auto=format&fit=crop&q=80',
    godName: 'Lord Vighnaharta Ganesha',
    festivalBannerUrl: 'https://images.unsplash.com/photo-1567591974584-f1832dfcad52?w=1200&auto=format&fit=crop&q=80',
    blessingQuote: 'वक्रतुण्ड महाकाय सूर्यकोटि समप्रभ। निर्विघ्नं कुरु मे देव सर्वकार्येषु सर्वदा॥',
    bgPattern: 'mandala',
    ambientEffect: 'diya-sparks',
    paletteClusters: ['#FF7700', '#D4AF37', '#E63946', '#210E07'],
  },

  // 6. GANESH CHATURTHI (LIGHT / SACRED SANDALWOOD)
  {
    id: 'ganesh-light',
    name: 'Ganesh Utsav Light (Temple Sandalwood & Kesari Gold)',
    festival: 'Ganesh Chaturthi / Vinayaka Chavithi',
    tagline: 'Pure Temple Sandalwood Ivory with Saffron Vermillion Accents',
    icon: '🐘',
    category: 'FESTIVAL',
    mode: 'LIGHT',
    primaryColor: '#C2410C',
    secondaryColor: '#B45309',
    accentColor: '#DC2626',
    backgroundColor: '#FFFDF9',
    cardBg: '#FFFFFF',
    textColor: '#1C1917',
    textMuted: '#78716C',
    glowColor: 'rgba(194, 65, 12, 0.35)',
    borderColor: 'rgba(180, 83, 9, 0.25)',
    announcementTicker: '🐘 Shubh Vinayaka Chavithi! Pure Unbroken W180 & W210 Cashews for Modak & Sweet Offerings',
    heroHeadline: 'Sacred Quality Cashews for Modak & Family Feasts',
    heroSubtitle: 'Naturally sweet and exceptionally crunchy whole cashews sourced with strict purity standards.',
    heroBadge: 'Vinayaka Blessings',
    godImageUrl: 'https://images.unsplash.com/photo-1567591974584-f1832dfcad52?w=600&auto=format&fit=crop&q=80',
    godName: 'Sidhi Vinayaka Blessings',
    festivalBannerUrl: 'https://images.unsplash.com/photo-1567591974584-f1832dfcad52?w=1200&auto=format&fit=crop&q=80',
    blessingQuote: 'May Lord Ganesha remove all obstacles and shower everlasting wisdom and prosperity upon you.',
    bgPattern: 'mandala',
    ambientEffect: 'golden-petals',
    paletteClusters: ['#C2410C', '#B45309', '#DC2626', '#FFFDF9'],
  },

  // 7. MAKAR SANKRANTI / PONGAL (LIGHT / HARVEST SUNSHINE)
  {
    id: 'sankranti-light',
    name: 'Makar Sankranti & Pongal (Sugarcane Green & Sun Gold)',
    festival: 'Makar Sankranti / Pongal',
    tagline: 'Lush Harvest Meadow Green with Radiant Sun Marigold Gold',
    icon: '🌾',
    category: 'FESTIVAL',
    mode: 'LIGHT',
    primaryColor: '#15803D',
    secondaryColor: '#D97706',
    accentColor: '#EA580C',
    backgroundColor: '#F8FCF8',
    cardBg: '#FFFFFF',
    textColor: '#0F172A',
    textMuted: '#64748B',
    glowColor: 'rgba(21, 128, 61, 0.35)',
    borderColor: 'rgba(217, 119, 6, 0.3)',
    announcementTicker: '🌾 Happy Sankranti & Pongal! Fresh Orchard Harvest Cashews Direct from Uppal Counter',
    heroHeadline: 'Auspicious Fresh Harvest Cashews & Traditional Treats',
    heroSubtitle: 'Directly sourced whole nuts prepared with the purity and crunch needed for festive sweets and family gatherings.',
    heroBadge: 'Harvest Festivity',
    godImageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',
    godName: 'Surya Bhagwan & Harvest Grains',
    festivalBannerUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=1200&auto=format&fit=crop&q=80',
    blessingQuote: 'मकर संक्रान्ति व पोंगल के पावन अवसर पर आपके घर में सुख, समृद्धि और मिठास की वर्षा हो!',
    bgPattern: 'rangoli',
    ambientEffect: 'golden-petals',
    paletteClusters: ['#15803D', '#D97706', '#EA580C', '#F8FCF8'],
  },

  // 8. EID MUBARAK (DARK / IMPERIAL OASIS)
  {
    id: 'eid-dark',
    name: 'Eid Mubarak (Imperial Oasis Emerald & Crescent Gold)',
    festival: 'Eid-ul-Fitr / Eid-ul-Adha',
    tagline: 'Imperial Oasis Emerald with Crescent Gold & Silken Cream',
    icon: '🌙',
    category: 'FESTIVAL',
    mode: 'DARK',
    primaryColor: '#059669',
    secondaryColor: '#D4AF37',
    accentColor: '#10B981',
    backgroundColor: '#04140D',
    cardBg: '#09251B',
    textColor: '#ECFDF5',
    textMuted: '#A7F3D0',
    glowColor: 'rgba(16, 185, 129, 0.45)',
    borderColor: 'rgba(212, 175, 55, 0.35)',
    announcementTicker: '🌙 Eid Mubarak! Premium W180 Jumbo Whole Cashews for Sheer Khurma & Royal Festive Gifting',
    heroHeadline: 'Royal Cashew Selections for Sheer Khurma & Eid Treats',
    heroSubtitle: 'Unmatched crunch and natural sweetness to make your Eid delicacies truly unforgettable.',
    heroBadge: 'Eid Festive Collection',
    godImageUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=600&auto=format&fit=crop&q=80',
    godName: 'Crescent Moon & Holy Sanctuary',
    festivalBannerUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=1200&auto=format&fit=crop&q=80',
    blessingQuote: 'تَقَبَّلَ اللّهُ مِنَّا وَ مِنْكُم • May Allah shower his countless blessings on you and your family.',
    bgPattern: 'crescent-stars',
    ambientEffect: 'crescent-stars',
    paletteClusters: ['#059669', '#D4AF37', '#10B981', '#09251B'],
  },

  // 9. EID MUBARAK (LIGHT / PEARL OASIS)
  {
    id: 'eid-light',
    name: 'Eid Moonlight Pearl (Silken Ivory & Oasis Emerald)',
    festival: 'Eid-ul-Fitr / Eid-ul-Adha',
    tagline: 'Serene Silken Pearl with Fresh Oasis Emerald & Gold Filigree',
    icon: '🌙',
    category: 'FESTIVAL',
    mode: 'LIGHT',
    primaryColor: '#047857',
    secondaryColor: '#B45309',
    accentColor: '#0D9488',
    backgroundColor: '#F2FCF7',
    cardBg: '#FFFFFF',
    textColor: '#064E3B',
    textMuted: '#4B5563',
    glowColor: 'rgba(4, 120, 87, 0.3)',
    borderColor: 'rgba(4, 120, 87, 0.2)',
    announcementTicker: '🌙 Eid Greetings! Luxury Cashew Gift Boxes & Sheer Khurma Nut Mix with Express Dispatch',
    heroHeadline: 'Pure & Wholesome Delights for Your Eid Gatherings',
    heroSubtitle: 'Finest handpicked jumbo cashews and rich nuts to sweeten your festive moments.',
    heroBadge: 'Eid Festive Edition',
    godImageUrl: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=600&auto=format&fit=crop&q=80',
    godName: 'Eid Oasis Serenity',
    festivalBannerUrl: 'https://images.unsplash.com/photo-1564769625905-50e93615e769?w=1200&auto=format&fit=crop&q=80',
    blessingQuote: 'Eid Mubarak! Wishing you peace, harmony, and joy on this sacred day.',
    bgPattern: 'crescent-stars',
    ambientEffect: 'crescent-stars',
    paletteClusters: ['#047857', '#B45309', '#0D9488', '#F2FCF7'],
  },

  // 10. NAVRATRI & DURGA PUJA (DARK / ROYAL SINDOOR)
  {
    id: 'navratri-dark',
    name: 'Navratri & Durga Puja (Royal Crimson Sindoor & Marigold)',
    festival: 'Navratri / Durga Puja / Dussehra',
    tagline: 'Fiery Sindoor Red with Marigold Glow & Sacred Energy',
    icon: '🪷',
    category: 'FESTIVAL',
    mode: 'DARK',
    primaryColor: '#E11D48',
    secondaryColor: '#F59E0B',
    accentColor: '#FFD700',
    backgroundColor: '#12050A',
    cardBg: '#240C16',
    textColor: '#FFF1F2',
    textMuted: '#FECDD3',
    glowColor: 'rgba(225, 29, 72, 0.45)',
    borderColor: 'rgba(245, 158, 11, 0.4)',
    announcementTicker: '🪷 Shubh Navratri! Fasting-Friendly Himalayan Salted & Raw Jumbo Cashews Available',
    heroHeadline: 'Pure Energy & Nutrition for Fasting & Festivities',
    heroSubtitle: '100% natural, protein-rich whole nuts hand-sorted for pure festive vitality and authentic taste.',
    heroBadge: 'Navratri Festive Edition',
    godImageUrl: 'https://images.unsplash.com/photo-1570535359195-bf436c84cce3?w=600&auto=format&fit=crop&q=80',
    godName: 'Maa Durga Shakti Swaroopa',
    festivalBannerUrl: 'https://images.unsplash.com/photo-1570535359195-bf436c84cce3?w=1200&auto=format&fit=crop&q=80',
    blessingQuote: 'सर्वमंगल मांगल्ये शिवे सर्वार्थ साधिके। शरण्ये त्र्यम्बके गौरि नारायणि नमोऽस्तु ते॥',
    bgPattern: 'lotus-waves',
    ambientEffect: 'golden-petals',
    paletteClusters: ['#E11D48', '#F59E0B', '#FFD700', '#240C16'],
  },

  // 11. JANMASHTAMI / RADHASTAMI (LIGHT / PEACOCK AZURE)
  {
    id: 'janmashtami-light',
    name: 'Janmashtami Divine (Peacock Azure & Makkhan Gold)',
    festival: 'Shri Krishna Janmashtami',
    tagline: 'Sacred Peacock Feather Azure with Butter Cream & Bansuri Gold',
    icon: '🦚',
    category: 'FESTIVAL',
    mode: 'LIGHT',
    primaryColor: '#0284C7',
    secondaryColor: '#D97706',
    accentColor: '#7C3AED',
    backgroundColor: '#F0F9FF',
    cardBg: '#FFFFFF',
    textColor: '#0C4A6E',
    textMuted: '#64748B',
    glowColor: 'rgba(2, 132, 199, 0.35)',
    borderColor: 'rgba(217, 119, 6, 0.25)',
    announcementTicker: '🦚 Jai Shri Krishna! Pure Cashew Kernels for Janmashtami Bhog & Dry Fruit Prasad',
    heroHeadline: 'Divine Handcrafted Cashews for Auspicious Krishna Bhog',
    heroSubtitle: 'Sweet, buttery whole cashews handpicked for festive sweets and prasad offerings.',
    heroBadge: 'Janmashtami Divine',
    godImageUrl: 'https://images.unsplash.com/photo-1582234372722-50d7ccc30ebd?w=600&auto=format&fit=crop&q=80',
    godName: 'Shri Krishna & Holy Flute',
    festivalBannerUrl: 'https://images.unsplash.com/photo-1582234372722-50d7ccc30ebd?w=1200&auto=format&fit=crop&q=80',
    blessingQuote: 'वसुदेवसुतं देवं कंसचाणूरमर्दनम्। देवकीपरमानन्दं कृष्णं वन्दे जगद्गुरुम्॥',
    bgPattern: 'lotus-waves',
    ambientEffect: 'peacock-aura',
    paletteClusters: ['#0284C7', '#D97706', '#7C3AED', '#F0F9FF'],
  },

  // 12. CHRISTMAS & NEW YEAR (LIGHT / WINTER CHAMPAGNE)
  {
    id: 'christmas-light',
    name: 'Christmas Joy (Cardinal Ruby & Champagne Evergreen)',
    festival: 'Christmas & New Year',
    tagline: 'Crisp Snow White with Rich Cardinal Ruby & Star Gold',
    icon: '🎄',
    category: 'SEASONAL',
    mode: 'LIGHT',
    primaryColor: '#DC2626',
    secondaryColor: '#15803D',
    accentColor: '#D97706',
    backgroundColor: '#FDFBFB',
    cardBg: '#FFFFFF',
    textColor: '#1F2937',
    textMuted: '#6B7280',
    glowColor: 'rgba(220, 38, 38, 0.3)',
    borderColor: 'rgba(21, 128, 61, 0.25)',
    announcementTicker: '🎄 Merry Christmas & Happy New Year! Luxury Holiday Cashew Gift Boxes Available with Express Dispatch',
    heroHeadline: 'Celebrate the Holidays with Artisanal Cashew Gifts',
    heroSubtitle: 'Handcrafted gift boxes with King Jumbo whole cashews, cinnamon roasts, and gourmet spiced party blends.',
    heroBadge: 'Holiday Season Edition',
    godImageUrl: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=600&auto=format&fit=crop&q=80',
    godName: 'Holiday Cheer & Festive Pine',
    festivalBannerUrl: 'https://images.unsplash.com/photo-1512389142860-9c449e58a543?w=1200&auto=format&fit=crop&q=80',
    blessingQuote: 'May your holiday season sparkle with moments of love, laughter, and goodwill.',
    bgPattern: 'snow-flakes',
    ambientEffect: 'snow-stars',
    paletteClusters: ['#DC2626', '#15803D', '#D97706', '#FDFBFB'],
  },

  // 13. SIGNATURE SVT ROASTERY (DARK / ROYAL 24K GOLD)
  {
    id: 'royal-gold',
    name: 'SVT Uppal Roastery Signature (Royal 24K Gold & Sapphire)',
    festival: 'Signature Standard',
    tagline: 'Signature Uppal Roastery 24K Gold & Deep Midnight Sapphire',
    icon: '👑',
    category: 'SIGNATURE',
    mode: 'DARK',
    primaryColor: '#D4AF37',
    secondaryColor: '#B48328',
    accentColor: '#38BDF8',
    backgroundColor: '#070D18',
    cardBg: '#0A111E',
    textColor: '#F8FAFC',
    textMuted: '#94A3B8',
    glowColor: 'rgba(212, 175, 55, 0.4)',
    borderColor: 'rgba(212, 175, 55, 0.3)',
    announcementTicker: '👑 Direct Uppal Roastery Counter • 100% Pure W180 Jumbo & Gourmet Spiced Cashews • Wholesale & Retail',
    heroHeadline: 'Supreme Quality Handpicked Cashews Direct from Uppal',
    heroSubtitle: 'Directly sourced from trusted orchards and freshly processed at our facility in Uppal, Hyderabad. Experience unmatched crunch and natural flavor.',
    heroBadge: 'Uppal Direct Roastery',
    godImageUrl: '/images/Header-logo.webp',
    godName: 'Sidhi Vinayaka Heritage',
    festivalBannerUrl: '/images/royal_cashew_roastery.webp',
    blessingQuote: 'Sidhi Vinayaka Traders • Delivering Purity, Crunch & Authentic Roastery Excellence.',
    bgPattern: 'mandala',
    ambientEffect: 'roastery-gold',
    paletteClusters: ['#D4AF37', '#B48328', '#38BDF8', '#0A111E'],
  },
];
